apiVersion: v1
kind: Namespace
metadata:
  name: goto-1
  namespace: goto-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goto-1
  namespace: goto-1
  labels:
    app: goto-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goto-1
  template:
    metadata:
      labels:
        app: goto-1
    spec:
      containers:
        - name: goto-1
          image: codydearkland/ld-demo-goto:1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: goto-1
  name: goto-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: goto-1
  type: LoadBalancer